makefile: introduce manifest to identify manipulation
this will check for a manifest file and verifies it with an
already installed binary. if it does not match install / update will abort.
if it matches or none is found a manifest will be created at the end

diff --git a/splunkhelper/Makefile b/splunkhelper/Makefile
--- a/splunkhelper/Makefile
+++ b/splunkhelper/Makefile
@@ -1,4 +1,5 @@
 BINFIX = /usr/local/bin
+MANF = /etc/shelper.manifest
 USER = root
 GROUP = root
 
@@ -16,20 +17,24 @@ LINKS = "shelperrestart \
 		shelperclustershowbundle \
 		shelperclusterlistpeers \
 		shelperdsreload \
-        shelperreload \
-        shelpershcshowstatus \
-        shelpershclistcaptain \
+		shelperreload \
+		shelpershcshowstatus \
+		shelpershclistcaptain \
 		shelperexchange"
 
 install:
+		if [ ${MANF} ]&&[ -f ${BINFIX}/shelper ];then
+		    md5sum -c ${MANF} || echo "ERROR: ${BINFIX}/shelper has been locally modified! aborted." && exit 9
+		fi
 		@install -o ${USER} -g ${GROUP} -m 0755 splunkhelper.in ${BINFIX}/shelper
 		for L in "${LINKS}";do \
 				ln -sfv ${BINFIX}/shelper ${BINFIX}/$$L ; \
 		done
 		sed -i "s#BINFIX#${BINFIX}#g" ${BINFIX}/shelper
+		md5sum ${BINFIX}/shelper > ${MANF}
 
 uninstall:
-		rm -fv ${BINFIX}/shelper ${BINFIX}/splunk*
+		rm -fv ${BINFIX}/shelper ${BINFIX}/splunk* ${MANF}
 		for L in "${LINKS}";do rm -vf ${BINFIX}/$$L ; done
 
 update: install
