make: moving manipulation check to own target & more
this introduces new make targets:

check -> manipulation detection
fulluninstall -> removes even local conf files like the new manifest

update target has been changed to:
check -> uninstall -> install

diff --git a/splunkhelper/Makefile b/splunkhelper/Makefile
--- a/splunkhelper/Makefile
+++ b/splunkhelper/Makefile
@@ -23,11 +23,19 @@ LINKS = "shelperrestart \
 		shelpershclistcaptain \
 		shelperexchange"
 
-install:
-		@if [ ${MANF} ]&&[ -f ${BINFIX}/shelper ];then \
-		    md5sum -c ${MANF} || ERR=$? ; \
-		    [ ${ERR} -ne 0 ] && echo "ERROR: ${BINFIX}/shelper has been locally modified! aborted." && exit 9 ; \
+check:
+		@echo "checking for manipulation ..."
+		@if [ -f ${MANF} ]&&[ -f ${BINFIX}/shelper ];then \
+		    md5sum -c ${MANF} ; ERR=$$? ; \
+		    if [ $$ERR -ne 0 ];then \
+			echo -e "ERROR: ${BINFIX}/shelper has been locally modified! aborted.\nIf you want to overwrite, remove ${MANF} manually and try again." ;\
+			exit 4 ;\
+		    else \
+			echo "check passed: ${BINFIX}/shelper has not been modified" ;\
+		    fi ;\
 		fi
+
+install:
 		@install -o ${USER} -g ${GROUP} -m 0755 splunkhelper.in ${BINFIX}/shelper
 		for L in "${LINKS}";do \
 				ln -sfv ${BINFIX}/shelper ${BINFIX}/$$L ; \
@@ -36,7 +44,10 @@ install:
 		md5sum ${BINFIX}/shelper > ${MANF}
 
 uninstall:
-		rm -fv ${BINFIX}/shelper ${BINFIX}/splunk* ${MANF}
+		rm -fv ${BINFIX}/shelper ${BINFIX}/splunk*
 		for L in "${LINKS}";do rm -vf ${BINFIX}/$$L ; done
 
-update: install
+fulluninstall: uninstall
+		rm -fv ${MANF}
+
+update: check uninstall install
