fix: some cosmetics in output

diff --git a/splunkhelper/usr-bin-splunk b/splunkhelper/usr-bin-splunk
--- a/splunkhelper/usr-bin-splunk
+++ b/splunkhelper/usr-bin-splunk
@@ -19,7 +19,7 @@
 #
 #########################################################################################
 #
-# Last changed: 2015-08-14
+# Last changed: 2015-08-25
 #
 #########################################################################################
 
@@ -113,7 +113,7 @@ case $BIN in
         [ ! "$ID" == "$SPLUSR" ] && echo -e "... will drop privileges to user <$SPLUSR>\n"
         if [ -z "$SHCMEMB" ];then
             while [ -z "$SHCMEMB" ];do
-                echo -e "\nHint: SHCMEMB variable is not defined in $BIN\n"
+                echo -e "\nHint: SHCMEMB variable is not defined in $BIN\nIf you like you can predefine a cluster member but it is recommended to define it manually here.\n"
                 read -p "Please specify 1 active SH cluster member (e.g.: '1.1.1.1' or 'my.fqdn.com') > " SHCMEMB
             done
         fi
@@ -130,13 +130,13 @@ case $BIN in
             echo -e "... dropping privileges to user <$SPLUSR>\n"
             su -c "$SPLBIN list master-info" - $SPLUSR > /dev/null
             MERR=$?
-            if [ $MERR -ne 0 ];then echo -e "\tERROR: This command can be executed on a Cluster Master only!\n" && exit $MERR ;fi
+            if [ $MERR -ne 0 ];then echo -e "\n\tERROR: This command can be executed on a Cluster Master only!\n" && exit $MERR ;fi
             su -c "$SPLBIN apply cluster-bundle" - $SPLUSR
         else
             echo
             "$SPLBIN" list master-info > /dev/null
              MERR=$?
-             if [ $MERR -ne 0 ];then echo -e "\tERROR: This command can be executed on a Cluster Master only!\n" && exit $MERR ;fi
+             if [ $MERR -ne 0 ];then echo -e "\n\tERROR: This command can be executed on a Cluster Master only!\n" && exit $MERR ;fi
             "$SPLBIN" apply cluster-bundle
         fi
         ;;
